package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/sahilpal/Nexus-TalentNetworkForTechnologyProfessionals/feed-svc/graph/model"
)

// FindPostByPostID is the resolver for the findPostByPostID field.
func (r *entityResolver) FindPostByPostID(ctx context.Context, postID string) (*model.Post, error) {
	panic(fmt.Errorf("not implemented: FindPostByPostID - findPostByPostID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
