package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/sahilpal/Nexus-TalentNetworkForTechnologyProfessionals/feed-svc/graph/model"
	feeddb "github.com/sahilpal/Nexus-TalentNetworkForTechnologyProfessionals/feed-svc/internal/db"
)

// FindPostByPostID is the resolver for the findPostByPostID field.
func (r *entityResolver) FindPostByPostID(ctx context.Context, postID string) (*model.Post, error) {
	posts, err := feeddb.GetPostsByIDs(ctx, r.DB, []string{postID})
	if err != nil || len(posts) == 0 {
		return nil, fmt.Errorf("post not found")
	}
	p := posts[0]
	return &model.Post{
		PostID:    p.PostID,
		UserID:    p.UserID,
		Content:   p.Content,
		CreatedAt: p.CreatedAt,
	}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
