package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/sahilpal/Nexus-TalentNetworkForTechnologyProfessionals/feed-svc/graph/model"
	"github.com/sahilpal/Nexus-TalentNetworkForTechnologyProfessionals/feed-svc/internal/auth"
	"github.com/sahilpal/Nexus-TalentNetworkForTechnologyProfessionals/feed-svc/internal/cache"
	feeddb "github.com/sahilpal/Nexus-TalentNetworkForTechnologyProfessionals/feed-svc/internal/db"
	"github.com/sahilpal/Nexus-TalentNetworkForTechnologyProfessionals/feed-svc/internal/kafka"
)

// CreatePost saves the post to Postgres and pushes it to the author's own feed in Redis.
func (r *mutationResolver) CreatePost(ctx context.Context, content string) (*model.Post, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("not authenticated")
	}

	p, err := feeddb.CreatePost(ctx, r.DB, userID, content)
	if err != nil {
		return nil, fmt.Errorf("failed to create post")
	}

	// Push to the author's own feed so they see their own posts
	_ = cache.PushToFeed(ctx, r.Redis, userID, p.PostID)
	go kafka.PublishPostCreated(context.Background(), p.PostID, userID, content)

	return &model.Post{
		PostID:    p.PostID,
		UserID:    p.UserID,
		Content:   p.Content,
		CreatedAt: p.CreatedAt,
	}, nil
}

// GetFeed reads the logged-in user's feed from Redis, then fetches full details from Postgres.
// Items can be posts (plain UUID) or jobs (prefixed with "job:")
func (r *queryResolver) GetFeed(ctx context.Context) ([]*model.FeedItem, error) {
	userID, ok := auth.UserIDFromContext(ctx)
	if !ok {
		return nil, fmt.Errorf("not authenticated")
	}

	ids, err := cache.GetFeed(ctx, r.Redis, userID)
	if err != nil {
		return nil, fmt.Errorf("failed to read feed")
	}

	var items []*model.FeedItem

	// separate post IDs and job IDs
	var postIDs []string
	var jobEntries []string
	for _, id := range ids {
		if len(id) > 4 && id[:4] == "job:" {
			jobEntries = append(jobEntries, id)
		} else {
			postIDs = append(postIDs, id)
		}
	}

	// fetch real posts from Postgres
	posts, err := feeddb.GetPostsByIDs(ctx, r.DB, postIDs)
	if err != nil {
		return nil, fmt.Errorf("failed to fetch posts")
	}
	for _, p := range posts {
		items = append(items, &model.FeedItem{
			PostID:    p.PostID,
			UserID:    p.UserID,
			Content:   p.Content,
			CreatedAt: p.CreatedAt,
		})
	}

	// fetch jobs from Postgres and show as feed items
	for _, entry := range jobEntries {
		jobID := entry[4:] // strip "job:" prefix
		j, err := feeddb.GetJobByID(ctx, r.DB, jobID)
		if err != nil {
			continue
		}
		items = append(items, &model.FeedItem{
			PostID:    "job:" + j.JobID,
			UserID:    j.PostedBy,
			Content:   "[JOB] " + j.Title + " at " + j.Company + " — " + j.Location,
			CreatedAt: j.CreatedAt,
		})
	}

	return items, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
