// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FeedItem struct {
	PostID    string `json:"post_id"`
	UserID    string `json:"user_id"`
	Content   string `json:"content"`
	CreatedAt string `json:"created_at"`
}

type Mutation struct {
}

type Post struct {
	PostID    string `json:"post_id"`
	UserID    string `json:"user_id"`
	Content   string `json:"content"`
	CreatedAt string `json:"created_at"`
}

type Query struct {
}
