// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FeedConnection struct {
	Edges    []*FeedEdge `json:"edges"`
	PageInfo *PageInfo   `json:"pageInfo"`
}

type FeedEdge struct {
	Cursor string    `json:"cursor"`
	Node   *FeedItem `json:"node"`
}

type FeedItem struct {
	PostID    string `json:"post_id"`
	UserID    string `json:"user_id"`
	Content   string `json:"content"`
	CreatedAt string `json:"created_at"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type Post struct {
	PostID    string `json:"post_id"`
	UserID    string `json:"user_id"`
	Content   string `json:"content"`
	CreatedAt string `json:"created_at"`
}

func (Post) IsEntity() {}

type Query struct {
}
