// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type ConnectionRequest struct {
	FromUserID string `json:"from_user_id"`
	ToUserID   string `json:"to_user_id"`
	Status     string `json:"status"`
}

type Mutation struct {
}

type PersonSuggestion struct {
	UserID      string `json:"user_id"`
	Name        string `json:"name"`
	Location    string `json:"location"`
	MutualCount int    `json:"mutual_count"`
}

func (PersonSuggestion) IsEntity() {}

type Query struct {
}
