// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type SearchResult interface {
	IsSearchResult()
}

type JobResult struct {
	JobID           string  `json:"job_id"`
	Title           string  `json:"title"`
	Company         string  `json:"company"`
	Location        *string `json:"location,omitempty"`
	JobType         string  `json:"job_type"`
	ExperienceLevel string  `json:"experience_level"`
}

func (JobResult) IsSearchResult() {}

type Query struct {
}

type UserResult struct {
	UserID   string  `json:"user_id"`
	Name     string  `json:"name"`
	Headline *string `json:"headline,omitempty"`
	Location *string `json:"location,omitempty"`
}

func (UserResult) IsSearchResult() {}
