// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Job struct {
	JobID           string  `json:"job_id"`
	PostedBy        *string `json:"posted_by,omitempty"`
	Title           string  `json:"title"`
	Company         string  `json:"company"`
	Location        *string `json:"location,omitempty"`
	JobType         string  `json:"job_type"`
	ExperienceLevel string  `json:"experience_level"`
	SalaryMin       *int    `json:"salary_min,omitempty"`
	SalaryMax       *int    `json:"salary_max,omitempty"`
	Description     string  `json:"description"`
	IsActive        bool    `json:"is_active"`
	CreatedAt       string  `json:"created_at"`
}

func (Job) IsEntity() {}

type JobConnection struct {
	Edges    []*JobEdge `json:"edges"`
	PageInfo *PageInfo  `json:"pageInfo"`
}

type JobEdge struct {
	Cursor string `json:"cursor"`
	Node   *Job   `json:"node"`
}

type Mutation struct {
}

type PageInfo struct {
	HasNextPage bool    `json:"hasNextPage"`
	EndCursor   *string `json:"endCursor,omitempty"`
}

type PostJobInput struct {
	Title           string  `json:"title"`
	Company         string  `json:"company"`
	Location        *string `json:"location,omitempty"`
	JobType         string  `json:"job_type"`
	ExperienceLevel string  `json:"experience_level"`
	SalaryMin       *int    `json:"salary_min,omitempty"`
	SalaryMax       *int    `json:"salary_max,omitempty"`
	Description     string  `json:"description"`
}

type Query struct {
}
