package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/sahilpal/Nexus-TalentNetworkForTechnologyProfessionals/search-svc/graph/model"
	"github.com/sahilpal/Nexus-TalentNetworkForTechnologyProfessionals/search-svc/internal/search"
)

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, query string) ([]model.SearchResult, error) {
	var results []model.SearchResult

	jobs, _ := search.SearchJobs(ctx, query)
	for _, j := range jobs {
		loc := &j.Location
		results = append(results, &model.JobResult{
			JobID:           j.JobID,
			Title:           j.Title,
			Company:         j.Company,
			Location:        loc,
			JobType:         j.JobType,
			ExperienceLevel: j.ExperienceLevel,
		})
	}

	users, _ := search.SearchUsers(ctx, query)
	for _, u := range users {
		headline := &u.Headline
		loc := &u.Location
		results = append(results, &model.UserResult{
			UserID:   u.UserID,
			Name:     u.Name,
			Headline: headline,
			Location: loc,
		})
	}

	return results, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
