package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/sahilpal/Nexus-TalentNetworkForTechnologyProfessionals/search-svc/graph/model"
)

// Search is the resolver for the search field.
func (r *queryResolver) Search(ctx context.Context, query string) ([]model.SearchResult, error) {
	return []model.SearchResult{}, nil
}

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
