// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	AccessToken  string `json:"access_token"`
	RefreshToken string `json:"refresh_token"`
	User         *User  `json:"user"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Query struct {
}

type RegisterInput struct {
	Email    string  `json:"email"`
	Password string  `json:"password"`
	Name     string  `json:"name"`
	Location *string `json:"location,omitempty"`
}

type Skill struct {
	SkillID  string `json:"skill_id"`
	Name     string `json:"name"`
	Endorsed int32  `json:"endorsed"`
}

type UpdateProfileInput struct {
	Name      *string `json:"name,omitempty"`
	Headline  *string `json:"headline,omitempty"`
	Bio       *string `json:"bio,omitempty"`
	Location  *string `json:"location,omitempty"`
	AvatarURL *string `json:"avatar_url,omitempty"`
}

type User struct {
	UserID    string   `json:"user_id"`
	Email     string   `json:"email"`
	Name      string   `json:"name"`
	Headline  *string  `json:"headline,omitempty"`
	Bio       *string  `json:"bio,omitempty"`
	Location  *string  `json:"location,omitempty"`
	AvatarURL *string  `json:"avatar_url,omitempty"`
	Skills    []*Skill `json:"skills"`
	CreatedAt string   `json:"created_at"`
}

func (User) IsEntity() {}
