-- Enable pgvector extension for semantic search (used in jobs service)
CREATE EXTENSION IF NOT EXISTS vector;

-- ============================================================
-- USERS
-- One row per registered user. This is the source of truth
-- for identity. Neo4j has a mirror (Person node) for graph
-- traversal, but this table owns the actual user data.
-- ============================================================
CREATE TABLE IF NOT EXISTS users (
    user_id       UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    email         TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,                  -- bcrypt hash, never plain text
    name          TEXT NOT NULL,
    headline      TEXT,                           -- "Backend Engineer at Razorpay"
    bio           TEXT,
    location      TEXT,
    avatar_url    TEXT,
    created_at    TIMESTAMPTZ DEFAULT NOW(),
    updated_at    TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- SKILLS
-- Master list of all skills (Go, Rust, Kafka, etc.)
-- Stored once here; users and jobs reference this table.
-- ============================================================
CREATE TABLE IF NOT EXISTS skills (
    skill_id  UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name      TEXT UNIQUE NOT NULL               -- "Go", "Rust", "Kafka"
);

-- ============================================================
-- USER_SKILLS
-- Which user has which skill. Many-to-many join table.
-- e.g. Sahil knows Go + Kafka → 2 rows here.
-- ============================================================
CREATE TABLE IF NOT EXISTS user_skills (
    user_id    UUID REFERENCES users(user_id) ON DELETE CASCADE,
    skill_id   UUID REFERENCES skills(skill_id) ON DELETE CASCADE,
    endorsed   INT DEFAULT 0,                    -- endorsement count
    PRIMARY KEY (user_id, skill_id)
);

-- ============================================================
-- CONNECTIONS
-- Tracks connection requests between users.
-- Status flows: PENDING → ACCEPTED or REJECTED
-- When ACCEPTED, Neo4j also gets a CONNECTED_TO edge.
-- ============================================================
CREATE TABLE IF NOT EXISTS connections (
    connection_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    sender_id     UUID REFERENCES users(user_id) ON DELETE CASCADE,
    receiver_id   UUID REFERENCES users(user_id) ON DELETE CASCADE,
    status        TEXT DEFAULT 'PENDING'          -- PENDING | ACCEPTED | REJECTED
                  CHECK (status IN ('PENDING','ACCEPTED','REJECTED')),
    created_at    TIMESTAMPTZ DEFAULT NOW(),
    updated_at    TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (sender_id, receiver_id)
);

-- ============================================================
-- JOBS
-- Job postings created by companies/recruiters.
-- Also indexed in Elasticsearch (keyword search) and
-- pgvector job_embeddings table (semantic search).
-- ============================================================
CREATE TABLE IF NOT EXISTS jobs (
    job_id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    posted_by        UUID REFERENCES users(user_id) ON DELETE SET NULL,
    title            TEXT NOT NULL,
    company          TEXT NOT NULL,
    location         TEXT,
    job_type         TEXT DEFAULT 'FULL_TIME'     -- FULL_TIME | PART_TIME | CONTRACT
                     CHECK (job_type IN ('FULL_TIME','PART_TIME','CONTRACT','INTERNSHIP')),
    experience_level TEXT DEFAULT 'MID'
                     CHECK (experience_level IN ('INTERN','JUNIOR','MID','SENIOR','LEAD')),
    salary_min       INT,
    salary_max       INT,
    description      TEXT NOT NULL,
    is_active        BOOLEAN DEFAULT TRUE,
    created_at       TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- JOB_SKILLS
-- Which skills a job requires. Many-to-many.
-- ============================================================
CREATE TABLE IF NOT EXISTS job_skills (
    job_id    UUID REFERENCES jobs(job_id) ON DELETE CASCADE,
    skill_id  UUID REFERENCES skills(skill_id) ON DELETE CASCADE,
    PRIMARY KEY (job_id, skill_id)
);

-- ============================================================
-- JOB_EMBEDDINGS
-- Stores the 1536-dimension vector for each job.
-- Generated by OpenAI embeddings API on job creation.
-- Used by pgvector for semantic similarity search.
-- "Find jobs similar in meaning to my query" — not just keywords.
-- ============================================================
CREATE TABLE IF NOT EXISTS job_embeddings (
    job_id    UUID PRIMARY KEY REFERENCES jobs(job_id) ON DELETE CASCADE,
    embedding vector(1536) NOT NULL
);

-- Index for fast cosine similarity search (HNSW algorithm)
CREATE INDEX IF NOT EXISTS job_embeddings_hnsw_idx
    ON job_embeddings USING hnsw (embedding vector_cosine_ops);

-- ============================================================
-- APPLICATIONS
-- Tracks who applied to which job.
-- Status: APPLIED → REVIEWING → ACCEPTED | REJECTED
-- ============================================================
CREATE TABLE IF NOT EXISTS applications (
    application_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    job_id         UUID REFERENCES jobs(job_id) ON DELETE CASCADE,
    applicant_id   UUID REFERENCES users(user_id) ON DELETE CASCADE,
    status         TEXT DEFAULT 'APPLIED'
                   CHECK (status IN ('APPLIED','REVIEWING','ACCEPTED','REJECTED')),
    cover_note     TEXT,
    applied_at     TIMESTAMPTZ DEFAULT NOW(),
    updated_at     TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE (job_id, applicant_id)               -- one application per job per user
);

-- ============================================================
-- POSTS
-- Content posted by users in their feed.
-- Stored here in Postgres; delivered via Redis sorted sets.
-- ============================================================
CREATE TABLE IF NOT EXISTS posts (
    post_id    UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    author_id  UUID REFERENCES users(user_id) ON DELETE CASCADE,
    content    TEXT NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ============================================================
-- REFRESH_TOKENS
-- Stores hashed refresh tokens for JWT auth.
-- When a user logs in, we issue access token (15min) +
-- refresh token (7 days). Refresh token hash is stored here.
-- ============================================================
CREATE TABLE IF NOT EXISTS refresh_tokens (
    token_id   UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id    UUID REFERENCES users(user_id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Indexes for common query patterns
CREATE INDEX IF NOT EXISTS idx_connections_receiver ON connections(receiver_id);
CREATE INDEX IF NOT EXISTS idx_connections_sender   ON connections(sender_id);
CREATE INDEX IF NOT EXISTS idx_posts_author         ON posts(author_id);
CREATE INDEX IF NOT EXISTS idx_jobs_company         ON jobs(company);
CREATE INDEX IF NOT EXISTS idx_applications_user    ON applications(applicant_id);
