package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/sahilpal/Nexus-TalentNetworkForTechnologyProfessionals/jobs-svc/graph/model"
	jobsdb "github.com/sahilpal/Nexus-TalentNetworkForTechnologyProfessionals/jobs-svc/internal/db"
)

// FindJobByJobID is the resolver for the findJobByJobID field.
func (r *entityResolver) FindJobByJobID(ctx context.Context, jobID string) (*model.Job, error) {
	j, err := jobsdb.GetJobByID(ctx, r.DB, jobID)
	if err != nil {
		return nil, fmt.Errorf("job not found")
	}
	return dbJobToModel(j), nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
