package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/sahilpal/Nexus-TalentNetworkForTechnologyProfessionals/jobs-svc/graph/model"
)

// FindJobByJobID is the resolver for the findJobByJobID field.
func (r *entityResolver) FindJobByJobID(ctx context.Context, jobID string) (*model.Job, error) {
	panic(fmt.Errorf("not implemented: FindJobByJobID - findJobByJobID"))
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
