package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"

	"github.com/sahilpal/Nexus-TalentNetworkForTechnologyProfessionals/network-svc/graph/model"
)

// FindPersonSuggestionByUserID is the resolver for the findPersonSuggestionByUserID field.
func (r *entityResolver) FindPersonSuggestionByUserID(ctx context.Context, userID string) (*model.PersonSuggestion, error) {
	return &model.PersonSuggestion{UserID: userID, Name: "", Location: "", MutualCount: 0}, nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
