package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.90

import (
	"context"
	"fmt"

	"github.com/sahilpal/Nexus-TalentNetworkForTechnologyProfessionals/profile-svc/graph/model"
	userdb "github.com/sahilpal/Nexus-TalentNetworkForTechnologyProfessionals/profile-svc/internal/db"
)

// FindUserByUserID is the resolver for the findUserByUserID field.
func (r *entityResolver) FindUserByUserID(ctx context.Context, userID string) (*model.User, error) {
	u, err := userdb.GetUserByID(ctx, r.DB, userID)
	if err != nil {
		return nil, fmt.Errorf("user not found")
	}
	return dbUserToModel(u), nil
}

// Entity returns EntityResolver implementation.
func (r *Resolver) Entity() EntityResolver { return &entityResolver{r} }

type entityResolver struct{ *Resolver }
